# Generated by Django 5.2.17 on 2026-09-25 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghs_per_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('provider', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('subscription', 'Subscription'), ('upgrade', 'Plan upgrade'), ('nfc_order', 'NFC order')], max_length=16)),
                ('months', models.PositiveSmallIntegerField(default=0)),
                ('subtotal_minor', models.PositiveIntegerField(default=0)),
                ('discount_minor', models.PositiveIntegerField(default=0)),
                ('tax_minor', models.PositiveIntegerField(default=0)),
                ('amount_minor', models.PositiveIntegerField(help_text='What the customer is charged, in pesewas.')),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], db_index=True, default='pending', max_length=24)),
                ('gateway', models.CharField(default='paystack', max_length=16)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('gateway_fee_minor', models.PositiveIntegerField(default=0)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('flag', models.CharField(blank=True, help_text='Set when verification found a problem.', max_length=64)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fx_rate_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('receipt_emailed_at', models.DateTimeField(blank=True, null=True)),
                ('manual_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('blurb', models.CharField(blank=True, max_length=160)),
                ('price_minor', models.PositiveIntegerField(help_text='Annual price in pesewas.')),
                ('duration_months', models.PositiveSmallIntegerField(default=12)),
                ('max_cards', models.PositiveSmallIntegerField(default=1)),
                ('max_phones', models.PositiveSmallIntegerField(default=2)),
                ('max_social_links', models.PositiveSmallIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True)),
                ('all_templates', models.BooleanField(default=False)),
                ('custom_colours', models.BooleanField(default=False)),
                ('shared_brand_theme', models.BooleanField(default=False)),
                ('allow_logo', models.BooleanField(default=False)),
                ('allow_advanced_style', models.BooleanField(default=False, help_text='Background image, button style and icon arrangement.')),
                ('branding_footer', models.CharField(choices=[('shown', 'Shown'), ('small', 'Shown (small)'), ('removable', 'Removable')], default='shown', max_length=16)),
                ('full_analytics', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price_minor'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('kind', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], max_length=8)),
                ('value', models.PositiveIntegerField(help_text='Percent (1-100) or amount in pesewas.')),
                ('applies_to', models.CharField(choices=[('subscription', 'Subscriptions'), ('nfc', 'NFC orders'), ('both', 'Both')], default='both', max_length=16)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('done', 'Refunded'), ('failed', 'Failed')], default='requested', max_length=16)),
                ('gateway_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('pending_plan_from', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
