# Generated by Django 5.2.17 on 2026-09-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='seats',
            field=models.PositiveIntegerField(blank=True, help_text='Team size bought, on team plans.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SeatBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_seats', models.PositiveIntegerField(help_text='First person in this band, e.g. 6.')),
                ('max_seats', models.PositiveIntegerField(blank=True, help_text='Last person in this band; empty for no limit.', null=True)),
                ('unit_price_minor', models.PositiveIntegerField(help_text='Yearly price of each person in this band, in pesewas.')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bands', to='billing.plan')),
            ],
            options={
                'ordering': ['min_seats'],
            },
        ),
    ]
