# Generated by Django 5.2.17 on 2026-09-25 05:19

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('fee_minor', models.PositiveIntegerField(default=0)),
                ('eta', models.CharField(help_text="For example '1–2 working days after dispatch'.", max_length=80)),
                ('is_pickup', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'fee_minor'],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price_minor', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('flat', 'Every card at this price'), ('incremental', 'Extra cards above the previous tier')], default='flat', max_length=12)),
            ],
            options={
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='NFCOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_confirmed', 'Payment confirmed'), ('design_pending', 'Design pending'), ('design_in_progress', 'Design in progress'), ('awaiting_approval', 'Awaiting your approval'), ('revision_requested', 'Revision requested'), ('on_hold', 'On hold'), ('approved', 'Design approved'), ('printing', 'Printing'), ('encoding_qc', 'Encoding and quality check'), ('ready_for_delivery', 'Ready for delivery'), ('ready_for_pickup', 'Ready for pickup'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending_payment', max_length=24)),
                ('quantity', models.PositiveIntegerField()),
                ('cards_minor', models.PositiveIntegerField(help_text='Card price for the whole quantity.')),
                ('delivery_fee_minor', models.PositiveIntegerField(default=0)),
                ('plan_minor', models.PositiveIntegerField(default=0, help_text='Subscription bought in the same checkout (NFL-03).')),
                ('discount_minor', models.PositiveIntegerField(default=0)),
                ('tax_minor', models.PositiveIntegerField(default=0)),
                ('total_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('full_name', models.CharField(max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('logo', models.FileField(blank=True, upload_to=apps.core.utils.keep_name)),
                ('reference_design', models.FileField(blank=True, upload_to=apps.core.utils.keep_name)),
                ('design_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recipient_name', models.CharField(blank=True, max_length=120)),
                ('recipient_phone', models.CharField(blank=True, max_length=32)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('delivery_gps', models.CharField(blank=True, max_length=16)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('courier_name', models.CharField(blank=True, max_length=80)),
                ('tracking_number', models.CharField(blank=True, max_length=80)),
                ('revision_rounds', models.PositiveSmallIntegerField(default=0)),
                ('accepted_refund_policy_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('awaiting_since', models.DateTimeField(blank=True, null=True)),
                ('qc_android_ok', models.BooleanField(default=False)),
                ('qc_iphone_ok', models.BooleanField(default=False)),
                ('qc_at', models.DateTimeField(blank=True, null=True)),
                ('tags_locked', models.BooleanField(default=False)),
                ('admin_notified_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('legacy_order_type', models.CharField(blank=True, max_length=32)),
                ('legacy_replacement_reason', models.CharField(blank=True, max_length=64)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundled_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan')),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nfc.deliveryzone')),
                ('qc_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfc_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFCOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfc_items', to='cards.card')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nfc.nfcorder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending_payment', 'Pending payment'), ('payment_confirmed', 'Payment confirmed'), ('design_pending', 'Design pending'), ('design_in_progress', 'Design in progress'), ('awaiting_approval', 'Awaiting your approval'), ('revision_requested', 'Revision requested'), ('on_hold', 'On hold'), ('approved', 'Design approved'), ('printing', 'Printing'), ('encoding_qc', 'Encoding and quality check'), ('ready_for_delivery', 'Ready for delivery'), ('ready_for_pickup', 'Ready for pickup'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=24)),
                ('message', models.TextField(blank=True)),
                ('visible_to_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nfc.nfcorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to=apps.core.utils.keep_name)),
                ('staff_note', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('pending', 'Waiting for customer'), ('approved', 'Approved'), ('changes_requested', 'Changes requested')], default='pending', max_length=20)),
                ('customer_comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='nfc.nfcorder')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('order', 'version')},
            },
        ),
    ]
