# Generated by Django 5.2.17 on 2026-09-25 08:47

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['is_international', 'sort_order', 'fee_minor']},
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='is_international',
            field=models.BooleanField(default=False, help_text='Shipping outside Ghana. The customer pays this fee for shipping and delivery; import duties in their country are theirs to pay.'),
        ),
        migrations.AddField(
            model_name='nfcorder',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='nfcorder',
            name='delivery_country',
            field=django_countries.fields.CountryField(blank=True, default='GH', max_length=2),
        ),
        migrations.AddField(
            model_name='nfcorder',
            name='delivery_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
