# Generated by Django 5.2.17 on 2026-09-25 05:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_days', models.PositiveSmallIntegerField(default=14)),
                ('reminder_days', models.CharField(default='30,7,1,0', help_text='Days before expiry to send renewal reminders; 0 means on the expiry date.', max_length=64)),
                ('data_retention_months', models.PositiveSmallIntegerField(default=12)),
                ('auto_purge_enabled', models.BooleanField(default=False, help_text='Delete personal data of cards inactive longer than the retention period. Leave off until the business has confirmed the retention policy.')),
                ('free_revision_rounds', models.PositiveSmallIntegerField(default=2)),
                ('proof_reminder_days', models.CharField(default='3,7', max_length=32)),
                ('on_hold_after_days', models.PositiveSmallIntegerField(default=14)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_label', models.CharField(blank=True, default='Tax', max_length=64)),
                ('fx_fallback_hours', models.PositiveSmallIntegerField(default=72)),
                ('leads_enabled', models.BooleanField(default=True)),
                ('support_phone', models.CharField(default='+233257932232', max_length=32)),
                ('support_whatsapp', models.CharField(default='+233545875881', max_length=32)),
                ('support_email', models.EmailField(default='adgraphics881@gmail.com', max_length=254)),
                ('instagram_handle', models.CharField(default='adgraphics__', max_length=64)),
                ('admin_notification_email', models.EmailField(default='adgraphics881@gmail.com', max_length=254)),
                ('office_address', models.CharField(blank=True, default='Cape Coast, Ghana', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('to', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(default='sent', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent_as_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
