# Generated by Django 5.2.17 on 2026-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='failed_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='reply_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
