# Generated by Django 5.2.17 on 2026-09-25 05:19

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.utils.keep_name)),
                ('title', models.CharField(help_text='The dark opening line under the slides, e.g. the client or project.', max_length=120)),
                ('description', models.CharField(blank=True, help_text='The grey sentence that runs on from the title.', max_length=240)),
                ('alt_text', models.CharField(blank=True, help_text='Describe the picture for people who cannot see it.', max_length=200)),
                ('caption', models.CharField(blank=True, help_text="Short label shown on the open slide, e.g. 'Flyer design'.", max_length=40)),
                ('action_label', models.CharField(blank=True, default='View design', max_length=40)),
                ('action_url', models.URLField(blank=True, help_text='Optional. Leave empty to open the full picture instead.')),
                ('focus', models.CharField(choices=[('center', 'Centre'), ('top', 'Top'), ('bottom', 'Bottom')], default='center', help_text='Which part of the picture stays in view when a slide is narrow.', max_length=8)),
                ('display_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
