# Generated by Django 5.2.17 on 2026-09-25 05:19

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('avatar', models.ImageField(blank=True, upload_to=apps.core.utils.keep_name)),
                ('logo', models.ImageField(blank=True, upload_to=apps.core.utils.keep_name)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('ghana_post_gps', models.CharField(blank=True, max_length=16)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hidden_fields', models.JSONField(blank=True, default=list)),
                ('template', models.CharField(choices=[('classic', 'Classic'), ('banner', 'Banner'), ('minimal', 'Minimal')], default='classic', max_length=16)),
                ('accent', models.CharField(default='#0048A9', max_length=7)),
                ('card_colour', models.CharField(blank=True, max_length=7)),
                ('background', models.ImageField(blank=True, upload_to=apps.core.utils.keep_name)),
                ('button_style', models.CharField(choices=[('pill', 'Pill'), ('rounded', 'Rounded'), ('square', 'Square')], default='pill', max_length=8)),
                ('icon_layout', models.CharField(choices=[('list', 'List'), ('grid', 'Grid'), ('row', 'Icon row')], default='list', max_length=8)),
                ('hide_branding', models.BooleanField(default=False)),
                ('allow_indexing', models.BooleanField(default=False)),
                ('collect_leads', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, help_text='For example MTN, Telecel or Office.', max_length=32)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='cards.card')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('impersonation', 'Impersonation'), ('fraud', 'Fraud or scam'), ('offensive', 'Offensive content'), ('other', 'Other')], max_length=16)),
                ('details', models.TextField(blank=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='open', max_length=16)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cards.card')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slug_history', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(default='link', max_length=8)),
                ('visitor_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cards.card')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('snapchat', 'Snapchat'), ('threads', 'Threads'), ('pinterest', 'Pinterest'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('github', 'GitHub'), ('behance', 'Behance'), ('researchgate', 'ResearchGate'), ('orcid', 'ORCID'), ('scholar', 'Google Scholar'), ('website', 'Website')], max_length=32)),
                ('url', models.URLField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='cards.card')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'View'), ('save_contact', 'Contact saved'), ('call', 'Phone click'), ('whatsapp', 'WhatsApp click'), ('email', 'Email click'), ('website', 'Website click'), ('social', 'Social click'), ('location', 'Location click')], db_index=True, max_length=16)),
                ('source', models.CharField(choices=[('link', 'Direct link'), ('qr', 'QR code'), ('nfc', 'NFC tap')], default='link', max_length=8)),
                ('detail', models.CharField(blank=True, max_length=32)),
                ('visitor_hash', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cards.card')),
            ],
            options={
                'indexes': [models.Index(fields=['card', 'occurred_at'], name='cards_carde_card_id_0356f5_idx')],
            },
        ),
    ]
