"""Cloudinary media storage.

Render's disk is wiped on every deploy, so uploaded pictures (card photos,
logos, gallery slides, NFC design files) live on Cloudinary in production.
Locally, FileSystemStorage is used instead; see STORAGES in settings.

Names are generated by the app as ``folder/<uuid>.<ext>`` and never reused,
so ``exists`` can safely report False and no name is ever overwritten.
"""

import os

import cloudinary
import cloudinary.uploader
import cloudinary.utils
import requests
from django.core.files.base import ContentFile
from django.core.files.storage import Storage
from django.utils.deconstruct import deconstructible

IMAGE_EXTENSIONS = {"jpg", "jpeg", "png", "webp", "gif"}


def _split(name):
    base, ext = os.path.splitext(name)
    return base, ext.lstrip(".").lower()


@deconstructible
class CloudinaryMediaStorage(Storage):
    def __init__(self):
        cloudinary.config(secure=True)  # reads CLOUDINARY_URL from the environment

    def _resource(self, name):
        _, ext = _split(name)
        return "image" if ext in IMAGE_EXTENSIONS else "raw"

    def _public_id(self, name):
        # Images are addressed without their extension; raw files keep it.
        base, _ = _split(name)
        return base if self._resource(name) == "image" else name

    def _save(self, name, content):
        name = name.replace("\\", "/")
        content.seek(0)
        cloudinary.uploader.upload(
            content,
            public_id=self._public_id(name),
            resource_type=self._resource(name),
            overwrite=False,
            unique_filename=False,
            use_filename=False,
        )
        return name

    def _open(self, name, mode="rb"):
        response = requests.get(self.url(name), timeout=30)
        response.raise_for_status()
        return ContentFile(response.content, name=name)

    def exists(self, name):
        return False

    def delete(self, name):
        if name:
            cloudinary.uploader.destroy(
                self._public_id(name), resource_type=self._resource(name), invalidate=True
            )

    def url(self, name):
        _, ext = _split(name)
        resource = self._resource(name)
        options = {"secure": True, "resource_type": resource}
        if resource == "image":
            options["format"] = ext
        url, _ = cloudinary.utils.cloudinary_url(self._public_id(name), **options)
        return url

    def size(self, name):
        return 0
